version: "3"

services:

  microservice:
    container_name: micro
    restart: "always"
    build: .
    environment:
      - VIRTUAL_HOST=rest.mpy.az
      - VIRTUAL_PORT=5052
    ports:
      - "5052:5052"
    volumes:
      - .:/code

networks:
  default:
    external:
      name: nginx-proxy
