version: "3"

services:

  microservice:
    container_name: micro
    restart: "always"
    build: .
    env_file: .env
    environment:
      - VIRTUAL_HOST=rest.mpy.az
      - VIRTUAL_PORT=5052
    volumes:
      - .:/code

