version: "3"

services:

  microservice:
    container_name: micro
    restart: "always"
    build: .
    environment:
      - VIRTUAL_HOST=example.com
      - VIRTUAL_PORT=5000
    volumes:
      - .:/code
      
